#!/usr/bin/env Rscript
# ─────────────────────────────────────────────────────────────────────────────
# run_all.R  —  Assemble the three section JSONs into the HTML-consumable JS.
#
# Writes  data/jobs-displacement-data.js  defining a global:
#   window.JOBS_DISPLACEMENT_DATA = { okun, age_bands, ces_slowdown, generated }
# consumed by jobs_displacement_prototype.html via <script src>.
#
# Usage:
#   Rscript data_analysis/scripts/run_all.R            # assemble from existing output/
#   Rscript data_analysis/scripts/run_all.R --refresh  # regenerate all data first
#
# Monthly job: run with --refresh, then commit data/jobs-displacement-data.js.
# ─────────────────────────────────────────────────────────────────────────────

suppressMessages(library(jsonlite))

repo     <- "/Users/mtkonczal/Documents/GitHub/ai-tech-markets-research"
scripts  <- file.path(repo, "data_analysis", "scripts")
out_dir  <- file.path(repo, "data_analysis", "output")
data_dir <- file.path(repo, "data")
dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)

if ("--refresh" %in% commandArgs(trailingOnly = TRUE)) {
  message("Refreshing all section data ...")
  for (s in c("01_okun.R", "02_age_bands.R", "03_ces_slowdown.R")) {
    message("  -> ", s)
    st <- system2("Rscript", file.path(scripts, s), stdout = FALSE, stderr = FALSE)
    if (st != 0) stop("Refresh failed on ", s)
  }
}

need <- c("okun.json", "age_bands.json", "ces_slowdown.json")
miss <- need[!file.exists(file.path(out_dir, need))]
if (length(miss)) stop("Missing section output(s): ", paste(miss, collapse = ", "),
                       "\nRun with --refresh or run the section scripts first.")

read_section <- function(f) fromJSON(file.path(out_dir, f), simplifyVector = FALSE)

payload <- list(
  generated = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
  okun         = read_section("okun.json"),
  age_bands    = read_section("age_bands.json"),
  ces_slowdown = read_section("ces_slowdown.json")
)

js <- paste0(
  "// AUTO-GENERATED by data_analysis/scripts/run_all.R -- do not edit by hand.\n",
  "// Regenerate: Rscript data_analysis/scripts/run_all.R --refresh\n",
  "window.JOBS_DISPLACEMENT_DATA = ",
  toJSON(payload, auto_unbox = TRUE, pretty = TRUE, digits = 6, null = "null"),
  ";\n"
)

target <- file.path(data_dir, "jobs-displacement-data.js")
writeLines(js, target)
cat("Wrote ", target, " (", format(file.info(target)$size, big.mark=","), " bytes)\n", sep = "")
