#!/usr/bin/env Rscript
# ─────────────────────────────────────────────────────────────────────────────
# run_exposure.R  —  serializer for the exposure x adoption exhibit (test T1).
#
# Writes  data/btos-exposure-data.js  defining a global:
#   window.BTOS_EXPOSURE = { vintage, source, exposure_meta, t1 }
# consumed by index.html (Adoption tab, section 01) via
# assets/adoption-charts.js.
#
# Replaces the upstream repo's run_micro.R, which serialized six tests (T1-T6)
# and pulled in QWI and CPS-panel metadata that this site does not ship. Only
# T1 crossed over, so this reads the three T1 CSVs directly rather than the
# whole micro build. Nothing here touches the network.
#
# Inputs:
#   micro/output/t1_adoption_exposure.csv   (48 industries x 7 metrics)
#   micro/output/t1_coefs.csv               (one row per exposure metric)
#   micro/output/t1_slope_over_time.csv     (one row per pre-break period)
#   exposure/output/exposure_meta.json      (provenance for the exposure build)
#
# Usage:  Rscript data_analysis/micro/run_exposure.R
# ─────────────────────────────────────────────────────────────────────────────

suppressMessages({ library(jsonlite); library(data.table) })

.file <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
repo  <- if (length(.file)) dirname(dirname(normalizePath(.file))) else normalizePath(getwd())
out   <- function(...) file.path(repo, "micro", "output", ...)
# `repo` is data_analysis/ in this layout; index.html reads data/ one level up.
data_dir <- file.path(dirname(repo), "data")
dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)

need <- c(out("t1_adoption_exposure.csv"), out("t1_coefs.csv"),
          out("t1_slope_over_time.csv"),
          file.path(repo, "exposure", "output", "exposure_meta.json"))
miss <- need[!file.exists(need)]
if (length(miss)) stop("Missing input(s):\n  ", paste(miss, collapse = "\n  "),
                       "\nRun exposure/02_build_exposure.R and micro/03_tests_industry.R first.")

# The scatter plots the PCA composite only; the other six metrics appear in the
# robustness table, which reads t1_coefs, so they are not needed point-by-point.
HEADLINE_METRIC <- "pca_score"

sc <- fread(out("t1_adoption_exposure.csv"))[metric == HEADLINE_METRIC]
if (!nrow(sc)) stop("No rows for metric '", HEADLINE_METRIC, "' in t1_adoption_exposure.csv")
sc <- sc[order(naics), .(naics, adopt = round(adopt, 4),
                         exposure_z = round(exposure_z, 6), pooled = as.logical(pooled))]

co <- fread(out("t1_coefs.csv"))[test == "T1"]
co <- co[, .(test, metric, n, slope_pp_per_sd = round(slope_pp_per_sd, 6),
             se = round(se, 6), p = signif(p, 3), r2 = round(r2, 6))]

tm <- fread(out("t1_slope_over_time.csv"))[order(date)]
tm <- tm[, .(date = as.character(date), slope = round(slope, 6),
             se = round(se, 6), r2 = round(r2, 6), n)]

# Benchmark held here rather than in the JS so the page never hard-codes a
# number that the pipeline does not also know about.
TUCKER_SLOPE <- 6.7
TUCKER_R2    <- 0.47

payload <- list(
  vintage = format(Sys.time(), "%Y-%m-%d %H:%M"),
  source = list(
    exposure = paste0("Budget Lab at Yale, AI-Effects replication (commit 4898eb3); composite PCA ",
                      "z-score over Felten-Raj-Seamans AIOE, Eloundou et al. GPT and human ratings, ",
                      "Eisfeldt-Schubert-Zhang total and core, and Microsoft AI applicability."),
    weighting = paste0("Occupation exposure aggregated to 3-digit NAICS using CPS 2021-22 ",
                       "occupation-by-industry employment shares (IPUMS basic monthly, WTFINL)."),
    adoption = paste0("BTOS 3-digit subsector AI-current Yes share, mean over the pre-break span ",
                      "(2023-09-11 to 2025-11-16), minimum 3 unsuppressed readings, pooled ",
                      "subsectors averaged with QWI employment weights.")
  ),
  exposure_meta = fromJSON(file.path(repo, "exposure", "output", "exposure_meta.json"),
                           simplifyVector = FALSE),
  t1 = list(
    coefs        = co,
    scatter      = sc,
    over_time    = tm,
    n            = nrow(sc),
    tucker_slope = TUCKER_SLOPE,
    tucker_r2    = TUCKER_R2
  )
)

js <- paste0(
  "// AUTO-GENERATED by data_analysis/micro/run_exposure.R -- do not edit by hand.\n",
  "// Regenerate: Rscript data_analysis/{exposure/02_build_exposure,micro/03_tests_industry,micro/run_exposure}.R\n",
  "window.BTOS_EXPOSURE = ",
  toJSON(payload, auto_unbox = TRUE, pretty = TRUE, digits = 6, null = "null"),
  ";\n"
)

target <- file.path(data_dir, "btos-exposure-data.js")
con <- file(target, open = "w", encoding = "UTF-8")
writeLines(enc2utf8(js), con, useBytes = TRUE)
close(con)
cat(sprintf("Wrote %s (%s bytes, %d industries, %d metrics, %d periods)\n",
            target, format(file.info(target)$size, big.mark = ","),
            nrow(sc), nrow(co), nrow(tm)))
