# ─────────────────────────────────────────────────────────────────────────────
# serialize.R — write a published contract.
#
# Every file under src/publish/ ends by calling write_js(). index.html loads
# each product as a classic <script src>, so the output is a plain assignment
# to a window global: no modules, no build step, works over file://.
#
# `digits` differs by contract and is NOT a free choice: it is the rounding the
# committed artifact was generated with. Changing it moves published numbers.
#   JOBS_DISPLACEMENT_DATA  6      BTOS_DATA          4
#   BTOS_JOBS_MONITOR       5      BTOS_EXPOSURE      6
#   JOBS_YOUNG_WORKERS      6  (also na = "null")
#
# ASCII only. R runs in the C locale on the maintainer's machine and mangles
# non-ASCII source bytes, so an em-dash written into a verdict string arrives
# in the browser as three garbage characters. write_js() refuses to write a
# non-ASCII payload rather than shipping mojibake.
# ─────────────────────────────────────────────────────────────────────────────

suppressPackageStartupMessages(library(jsonlite))

write_js <- function(payload, global, target, regenerate_with,
                     digits = 6, na = "string") {
  js <- paste0(
    "// AUTO-GENERATED by ", regenerate_with, " -- do not edit by hand.\n",
    "// Regenerate: ", regenerate_with, "\n",
    "window.", global, " = ",
    toJSON(payload, auto_unbox = TRUE, pretty = TRUE,
           digits = digits, null = "null", na = na),
    ";\n"
  )

  bad <- grepl("[^\x01-\x7F]", js, useBytes = TRUE)
  if (bad) {
    lines <- strsplit(js, "\n", fixed = TRUE)[[1]]
    hits  <- head(which(grepl("[^\x01-\x7F]", lines, useBytes = TRUE)), 5)
    stop("Refusing to write non-ASCII to ", basename(target), ".\n",
         "  First offending line(s):\n    ",
         paste(trimws(lines[hits]), collapse = "\n    "),
         "\n  Replace the character with its ASCII equivalent, or an HTML",
         " entity if the site should render a symbol.", call. = FALSE)
  }

  # Write UTF-8 explicitly. Plain writeLines() uses the session's native
  # encoding, which on a non-UTF-8 locale corrupts multibyte characters.
  con <- file(target, open = "w", encoding = "UTF-8")
  on.exit(close(con), add = TRUE)
  writeLines(enc2utf8(js), con, useBytes = TRUE)

  invisible(target)
}

# Read a card's JSON fragment written by an exhibit. Exhibits write to
# interim/cards/<name>.json; publishers assemble those into one contract.
read_card <- function(name) {
  p <- card_path(paste0(name, ".json"))
  if (!file.exists(p))
    stop("Missing card fragment ", basename(p),
         "\n  Run its exhibit first: analysis/src/exhibits/", name, ".R",
         call. = FALSE)
  fromJSON(p, simplifyVector = FALSE)
}

# Write a card's JSON fragment. Called at the end of every exhibit.
#
# na = "null" is not optional. Without it jsonlite serialises R's NA as the
# STRING "NA", which survives all the way to the browser, where it is truthy
# and a chart will try to plot it. A missing observation must arrive as JSON
# null so `if (v == null)` in the chart code does the right thing.
write_card <- function(payload, name, digits = 6) {
  ensure_dir(card_path())
  p <- card_path(paste0(name, ".json"))
  write_json(payload, p, auto_unbox = TRUE, pretty = TRUE,
             digits = digits, na = "null")
  say("  wrote %s", p)
  invisible(p)
}
