#!/usr/bin/env Rscript
# ─────────────────────────────────────────────────────────────────────────────
# run_btos.R  —  Stage 3: wrap btos_data.json as the browser-consumable JS.
#
# Writes  data/btos-data.js  defining a global:
#   window.BTOS_DATA = { ... }
# consumed by btos.html via <script src="data/btos-data.js">.
#
# Assumes stages 1–2 have run. Does not touch the network.
#
# Usage:  Rscript btos/run_btos.R
# ─────────────────────────────────────────────────────────────────────────────

suppressMessages(library(jsonlite))

.file    <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
repo     <- if (length(.file)) dirname(dirname(normalizePath(.file))) else normalizePath(getwd())
src      <- file.path(repo, "btos", "output", "btos_data.json")
# `repo` is data_analysis/ in this layout; index.html reads data/ at the site
# root, one level up. Keep these two in step if the tree ever moves.
data_dir <- file.path(dirname(repo), "data")
dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)

if (!file.exists(src)) stop("Missing ", src, " — run 02_build_btos.R first.")

payload <- fromJSON(src, simplifyVector = FALSE)

js <- paste0(
  "// AUTO-GENERATED by data_analysis/btos/run_btos.R -- do not edit by hand.\n",
  "// Regenerate: Rscript data_analysis/btos/{01_fetch_btos,02_build_btos,run_btos}.R\n",
  "window.BTOS_DATA = ",
  toJSON(payload, auto_unbox = TRUE, pretty = TRUE, digits = 4, null = "null"),
  ";\n"
)

target <- file.path(data_dir, "btos-data.js")
# Write UTF-8 explicitly. Plain writeLines() uses the session's native encoding,
# which on a non-UTF-8 locale corrupts multibyte characters (e.g. an em-dash
# becomes stray 0x80 0x94 bytes). enc2utf8 + a UTF-8 connection keeps any
# non-ASCII in the data (accented titles, symbols) intact in the browser.
con <- file(target, open = "w", encoding = "UTF-8")
writeLines(enc2utf8(js), con, useBytes = TRUE)
close(con)
cat(sprintf("Wrote %s (%s bytes)\n", target,
            format(file.info(target)$size, big.mark = ",")))
