#!/usr/bin/env Rscript
# ─────────────────────────────────────────────────────────────────────────────
# run_jobs.R  —  Tier 4 serializer.
#
# Writes  data/btos-jobs-monitor-data.js  defining a global:
#   window.BTOS_JOBS_MONITOR = { ... }
# consumed by index.html (Job Displacement tab, section 04 "Freeze or shed")
# via assets/jobs-monitor-charts.js.
#
# This is a SLICE of btos_jobs.json, not the whole thing. The upstream research
# repo shipped a four-tab dashboard off the full object (all 96 cross-section
# coefficients, the panel, the AV plot, the placebos). This site uses only the
# descriptive monitor, so we ship ~44 KB instead of ~255 KB and the regression
# machinery stays in btos/output/ for anyone who wants it. If you add an exhibit
# that needs another block, add its key to MONITOR_KEEP or TOP_KEEP below.
#
# Assumes btos/03_jobs_join.R has run. Does not touch the network.
#
# Usage:  Rscript data_analysis/btos/run_jobs.R
# ─────────────────────────────────────────────────────────────────────────────

suppressMessages(library(jsonlite))

.file    <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
repo     <- if (length(.file)) dirname(dirname(normalizePath(.file))) else normalizePath(getwd())
src      <- file.path(repo, "btos", "output", "btos_jobs.json")
# `repo` is data_analysis/ in this layout; index.html reads data/ at the site
# root, one level up. Keep these two in step if the tree ever moves.
data_dir <- file.path(dirname(repo), "data")
dir.create(data_dir, showWarnings = FALSE, recursive = TRUE)

if (!file.exists(src)) stop("Missing ", src, " - run 03_jobs_join.R first.")

full <- fromJSON(src, simplifyVector = FALSE)

TOP_KEEP     <- c("vintage", "ces_latest", "jolts_latest", "counts", "jolts_groups")
MONITOR_KEEP <- c("board", "decomp", "quad", "mde", "scorecard", "nat_adopt",
                  "total_private_chg")

miss <- setdiff(TOP_KEEP, names(full))
if (length(miss)) stop("btos_jobs.json is missing: ", paste(miss, collapse = ", "))
miss <- setdiff(MONITOR_KEEP, names(full$monitor))
if (length(miss)) stop("btos_jobs.json$monitor is missing: ", paste(miss, collapse = ", "))

payload <- full[TOP_KEEP]
payload$monitor <- full$monitor[MONITOR_KEEP]

js <- paste0(
  "// AUTO-GENERATED by data_analysis/btos/run_jobs.R -- do not edit by hand.\n",
  "// Regenerate: Rscript data_analysis/btos/{03_jobs_join,run_jobs}.R\n",
  "window.BTOS_JOBS_MONITOR = ",
  toJSON(payload, auto_unbox = TRUE, pretty = TRUE, digits = 5, null = "null"),
  ";\n"
)

target <- file.path(data_dir, "btos-jobs-monitor-data.js")
# UTF-8 explicitly: plain writeLines() uses the session's native encoding, which
# on a non-UTF-8 locale corrupts multibyte characters.
con <- file(target, open = "w", encoding = "UTF-8")
writeLines(enc2utf8(js), con, useBytes = TRUE)
close(con)
cat(sprintf("Wrote %s (%s bytes)\n", target,
            format(file.info(target)$size, big.mark = ",")))
